import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import waitingForFood from "../public/waiting-for-food.jpg"
import PaymentService from '../service/paymentService'

const Home: NextPage = () => {

  const handlePayment = () => {
    PaymentService.sslCommerzRequest({
      name: "coffee",
      price: 150
    }).then((response: any) => {
      window.location = response.data; 
    });
      
    
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image src={waitingForFood} alt='image'/>
        <p className={styles.description}>
          Buy me a coffee <input type='button' value={"Pay now"}  className={styles.pay} onClick={event => handlePayment()}/>
        </p>
      </main>
    </div>
  )
}

export default Home
